spring:
  config:
    import: file:./.env.dev[.properties]
  flyway:
    clean-disabled: true
    enabled: true
  datasource:
    url: ${LMEE_POSTGRES_DB}
    username: ${LMEE_POSTGRES_USER}
    password: ${LMEE_POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      lifecycle-management: start_and_stop
lmee:
  cors:
    allowed-origin-patterns: http://localhost:*,http://127.0.0.1:*

error:
  handling:
    exception-logging: WITH_STACKTRACE
    log-levels:
      4xx: WARN
      5xx: ERROR
