spring:
  config:
    import: optional:file:../.env.dev[.properties]
  flyway:
    clean-disabled: true
    enabled: true
  datasource:
    url: ${LMEE_POSTGRES_DB}
    username: ${LMEE_POSTGRES_USER}
    password: ${LMEE_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      lifecycle-management: start_and_stop
error:
  handling:
    exception-logging: WITH_STACKTRACE
    log-levels:
      4xx: WARN
      5xx: ERROR
