spring:
  config:
    import: optional:file:../.env[.properties]
  flyway:
    clean-disabled: true
    enabled: true
  datasource:
    url: ${LMEE_POSTGRES_DB}
    username: ${LMEE_POSTGRES_USER}
    password: ${LMEE_POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jpa:
    hibernate:
      ddl-auto: validate

lmee:
  cors:
    allowed-origin-patterns: https://zealous-dune-00b527710.5.azurestaticapps.net

error:
  handling:
    exception-logging: MESSAGE_ONLY
    full-stacktrace-http-statuses: 5xx
    log-levels:
      400: DEBUG
      404: DEBUG
      409: INFO
      422: INFO
      401: WARN
      403: WARN
      5xx: ERROR
