### POST /matches/{id}/events needs OPERATOR.
@matchId = 671eaf85-f7da-48c2-9ee9-cacca507ce04

POST http://localhost:8080/matches/{{matchId}}/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "MATCH_STARTED"
}
