package com.raid.lmee.model;


public enum MatchEventType {

    MATCH_SCHEDULED,
    MATCH_STARTED,
    FIRST_HALF_ENDED,
    SECOND_HALF_STARTED,
    FULL_TIME,
    MATCH_ABANDONED,
    MATCH_POSTPONED,
    GOAL_SCORED,
    OWN_GOAL,
    GOAL_CANCELED,
    YELLOW_CARD_GIVEN,
    RED_CARD_GIVEN,
    SECOND_YELLOW_CARD,
    SUBSTITUTION,
    PENALTY_AWARDED,
    PENALTY_SCORED,
    PENALTY_MISSED,
    VAR_CHECK_STARTED,
    VAR_DECISION,
    ADDED_TIME_ANNOUNCED

}
