name: deploy.yml
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: lmeecr
  ACR_LOGIN_SERVER: lmeecr.azurecr.io
  ACA_APP_NAME: backend
  RESOURCE_GROUP: lmee-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: "temurin"

      - name: Build
        run: mvn clean package

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push the docker image
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Update container app revision
        run: |
          az containerapp update \
            --name ${{ env.ACA_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
